package com.qingyun.mybatis.model;

public class MbShoppingmall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_shoppingmall.ShoppingMallId
     *
     * @mbggenerated
     */
    private Long shoppingmallid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_shoppingmall.ShoppingMallPic
     *
     * @mbggenerated
     */
    private String shoppingmallpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_shoppingmall.ShoppingMallContent
     *
     * @mbggenerated
     */
    private String shoppingmallcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_shoppingmall.ShoppingMallId
     *
     * @return the value of mb_shoppingmall.ShoppingMallId
     *
     * @mbggenerated
     */
    public Long getShoppingmallid() {
        return shoppingmallid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_shoppingmall.ShoppingMallId
     *
     * @param shoppingmallid the value for mb_shoppingmall.ShoppingMallId
     *
     * @mbggenerated
     */
    public void setShoppingmallid(Long shoppingmallid) {
        this.shoppingmallid = shoppingmallid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_shoppingmall.ShoppingMallPic
     *
     * @return the value of mb_shoppingmall.ShoppingMallPic
     *
     * @mbggenerated
     */
    public String getShoppingmallpic() {
        return shoppingmallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_shoppingmall.ShoppingMallPic
     *
     * @param shoppingmallpic the value for mb_shoppingmall.ShoppingMallPic
     *
     * @mbggenerated
     */
    public void setShoppingmallpic(String shoppingmallpic) {
        this.shoppingmallpic = shoppingmallpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_shoppingmall.ShoppingMallContent
     *
     * @return the value of mb_shoppingmall.ShoppingMallContent
     *
     * @mbggenerated
     */
    public String getShoppingmallcontent() {
        return shoppingmallcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_shoppingmall.ShoppingMallContent
     *
     * @param shoppingmallcontent the value for mb_shoppingmall.ShoppingMallContent
     *
     * @mbggenerated
     */
    public void setShoppingmallcontent(String shoppingmallcontent) {
        this.shoppingmallcontent = shoppingmallcontent;
    }
}