package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.SysProblem;
import com.qingyun.mybatis.model.SysProblemExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int countByExample(SysProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int deleteByExample(SysProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long problemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int insert(SysProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int insertSelective(SysProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    List<SysProblem> selectByExample(SysProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    SysProblem selectByPrimaryKey(Long problemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysProblem record, @Param("example") SysProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysProblem record, @Param("example") SysProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysProblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_problem
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysProblem record);

    List<SysProblem> getListByHDPage(Map<String, Object> map);

    List<SysProblem> getProblem();
}