package com.qingyun.mybatis.model;

import java.util.Date;

public class SysProblem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemId
     *
     * @mbggenerated
     */
    private Long problemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemTitle
     *
     * @mbggenerated
     */
    private String problemtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemRemarks
     *
     * @mbggenerated
     */
    private String problemremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemAnswer
     *
     * @mbggenerated
     */
    private String problemanswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemStats
     *
     * @mbggenerated
     */
    private Integer problemstats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.ProblemSort
     *
     * @mbggenerated
     */
    private Integer problemsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_problem.IsDel
     *
     * @mbggenerated
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemId
     *
     * @return the value of sys_problem.ProblemId
     *
     * @mbggenerated
     */
    public Long getProblemid() {
        return problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemId
     *
     * @param problemid the value for sys_problem.ProblemId
     *
     * @mbggenerated
     */
    public void setProblemid(Long problemid) {
        this.problemid = problemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemTitle
     *
     * @return the value of sys_problem.ProblemTitle
     *
     * @mbggenerated
     */
    public String getProblemtitle() {
        return problemtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemTitle
     *
     * @param problemtitle the value for sys_problem.ProblemTitle
     *
     * @mbggenerated
     */
    public void setProblemtitle(String problemtitle) {
        this.problemtitle = problemtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemRemarks
     *
     * @return the value of sys_problem.ProblemRemarks
     *
     * @mbggenerated
     */
    public String getProblemremarks() {
        return problemremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemRemarks
     *
     * @param problemremarks the value for sys_problem.ProblemRemarks
     *
     * @mbggenerated
     */
    public void setProblemremarks(String problemremarks) {
        this.problemremarks = problemremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemAnswer
     *
     * @return the value of sys_problem.ProblemAnswer
     *
     * @mbggenerated
     */
    public String getProblemanswer() {
        return problemanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemAnswer
     *
     * @param problemanswer the value for sys_problem.ProblemAnswer
     *
     * @mbggenerated
     */
    public void setProblemanswer(String problemanswer) {
        this.problemanswer = problemanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemStats
     *
     * @return the value of sys_problem.ProblemStats
     *
     * @mbggenerated
     */
    public Integer getProblemstats() {
        return problemstats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemStats
     *
     * @param problemstats the value for sys_problem.ProblemStats
     *
     * @mbggenerated
     */
    public void setProblemstats(Integer problemstats) {
        this.problemstats = problemstats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.CreateTime
     *
     * @return the value of sys_problem.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.CreateTime
     *
     * @param createtime the value for sys_problem.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.ProblemSort
     *
     * @return the value of sys_problem.ProblemSort
     *
     * @mbggenerated
     */
    public Integer getProblemsort() {
        return problemsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.ProblemSort
     *
     * @param problemsort the value for sys_problem.ProblemSort
     *
     * @mbggenerated
     */
    public void setProblemsort(Integer problemsort) {
        this.problemsort = problemsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_problem.IsDel
     *
     * @return the value of sys_problem.IsDel
     *
     * @mbggenerated
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_problem.IsDel
     *
     * @param isdel the value for sys_problem.IsDel
     *
     * @mbggenerated
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}