package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.KeyWord;
import com.qingyun.mybatis.model.KeyWordExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface KeyWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int countByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int deleteByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long keywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int insert(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int insertSelective(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    List<KeyWord> selectByExample(KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    KeyWord selectByPrimaryKey(Long keywordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") KeyWord record, @Param("example") KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") KeyWord record, @Param("example") KeyWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_word
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyWord record);

    List<KeyWord> getKeyWordHDPage(Map<String,Object> map);
}