package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.MbBackgroundPic;
import com.qingyun.mybatis.model.MbBackgroundPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MbBackgroundPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int countByExample(MbBackgroundPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int deleteByExample(MbBackgroundPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long backgroundpicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int insert(MbBackgroundPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int insertSelective(MbBackgroundPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    List<MbBackgroundPic> selectByExample(MbBackgroundPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    MbBackgroundPic selectByPrimaryKey(Long backgroundpicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MbBackgroundPic record, @Param("example") MbBackgroundPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MbBackgroundPic record, @Param("example") MbBackgroundPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MbBackgroundPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_background_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MbBackgroundPic record);
}