package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.MbCooperativepartner;
import com.qingyun.mybatis.model.MbCooperativepartnerExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MbCooperativepartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int countByExample(MbCooperativepartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int deleteByExample(MbCooperativepartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long cooperativepartnerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int insert(MbCooperativepartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int insertSelective(MbCooperativepartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    List<MbCooperativepartner> selectByExample(MbCooperativepartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    MbCooperativepartner selectByPrimaryKey(Long cooperativepartnerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MbCooperativepartner record, @Param("example") MbCooperativepartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MbCooperativepartner record, @Param("example") MbCooperativepartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MbCooperativepartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MbCooperativepartner record);

    List<MbCooperativepartner> getListByHDPage(Map<String, Object> map);

    List<MbCooperativepartner> getCooperativePartner();
}