package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.MbProductIntroduction;
import com.qingyun.mybatis.model.MbProductIntroductionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MbProductIntroductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int countByExample(MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int deleteByExample(MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int insert(MbProductIntroduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int insertSelective(MbProductIntroduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    List<MbProductIntroduction> selectByExampleWithBLOBs(MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    List<MbProductIntroduction> selectByExample(MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    MbProductIntroduction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MbProductIntroduction record, @Param("example") MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MbProductIntroduction record, @Param("example") MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MbProductIntroduction record, @Param("example") MbProductIntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MbProductIntroduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MbProductIntroduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_product_introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MbProductIntroduction record);
}