package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.SysBasics;
import com.qingyun.mybatis.model.SysBasicsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysBasicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int countByExample(SysBasicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int deleteByExample(SysBasicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int insert(SysBasics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int insertSelective(SysBasics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    List<SysBasics> selectByExample(SysBasicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    SysBasics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysBasics record, @Param("example") SysBasicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysBasics record, @Param("example") SysBasicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysBasics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_basics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysBasics record);
}