package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.SysFrinedshiplink;
import com.qingyun.mybatis.model.SysFrinedshiplinkExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysFrinedshiplinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int countByExample(SysFrinedshiplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int deleteByExample(SysFrinedshiplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long friendshiplinkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int insert(SysFrinedshiplink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int insertSelective(SysFrinedshiplink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    List<SysFrinedshiplink> selectByExample(SysFrinedshiplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    SysFrinedshiplink selectByPrimaryKey(Long friendshiplinkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysFrinedshiplink record, @Param("example") SysFrinedshiplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysFrinedshiplink record, @Param("example") SysFrinedshiplinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysFrinedshiplink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_frinedshiplink
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysFrinedshiplink record);

    List<SysFrinedshiplink> getFriendshipLinkHDPage(Map<String,Object> map);
}