package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.SysOpinionback;
import com.qingyun.mybatis.model.SysOpinionbackExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysOpinionbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int countByExample(SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int deleteByExample(SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long opinionbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int insert(SysOpinionback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int insertSelective(SysOpinionback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    List<SysOpinionback> selectByExampleWithBLOBs(SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    List<SysOpinionback> selectByExample(SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    SysOpinionback selectByPrimaryKey(Long opinionbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysOpinionback record, @Param("example") SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SysOpinionback record, @Param("example") SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysOpinionback record, @Param("example") SysOpinionbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysOpinionback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SysOpinionback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_opinionback
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysOpinionback record);

    List<SysOpinionback> getListByHDPage(Map<String, Object> map);
}