package com.qingyun.mybatis.model;

import java.util.Date;

public class MbCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_phone
     *
     * @mbggenerated
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_time
     *
     * @mbggenerated
     */
    private String customerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_status
     *
     * @mbggenerated
     */
    private Integer customerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_customer.customer_pic
     *
     * @mbggenerated
     */
    private String customerPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_id
     *
     * @return the value of mb_customer.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_id
     *
     * @param customerId the value for mb_customer.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_name
     *
     * @return the value of mb_customer.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_name
     *
     * @param customerName the value for mb_customer.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_phone
     *
     * @return the value of mb_customer.customer_phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_phone
     *
     * @param customerPhone the value for mb_customer.customer_phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_time
     *
     * @return the value of mb_customer.customer_time
     *
     * @mbggenerated
     */
    public String getCustomerTime() {
        return customerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_time
     *
     * @param customerTime the value for mb_customer.customer_time
     *
     * @mbggenerated
     */
    public void setCustomerTime(String customerTime) {
        this.customerTime = customerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_status
     *
     * @return the value of mb_customer.customer_status
     *
     * @mbggenerated
     */
    public Integer getCustomerStatus() {
        return customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_status
     *
     * @param customerStatus the value for mb_customer.customer_status
     *
     * @mbggenerated
     */
    public void setCustomerStatus(Integer customerStatus) {
        this.customerStatus = customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.create_time
     *
     * @return the value of mb_customer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.create_time
     *
     * @param createTime the value for mb_customer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.edit_time
     *
     * @return the value of mb_customer.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.edit_time
     *
     * @param editTime the value for mb_customer.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_customer.customer_pic
     *
     * @return the value of mb_customer.customer_pic
     *
     * @mbggenerated
     */
    public String getCustomerPic() {
        return customerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_customer.customer_pic
     *
     * @param customerPic the value for mb_customer.customer_pic
     *
     * @mbggenerated
     */
    public void setCustomerPic(String customerPic) {
        this.customerPic = customerPic;
    }
}