package com.qingyun.mybatis.model;

import java.util.Date;

public class MbIp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_ip.IpId
     *
     * @mbggenerated
     */
    private Long ipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_ip.IpAddress
     *
     * @mbggenerated
     */
    private String ipaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_ip.AccessTime
     *
     * @mbggenerated
     */
    private Date accesstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_ip.IpStats
     *
     * @mbggenerated
     */
    private Short ipstats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_ip.IpId
     *
     * @return the value of mb_ip.IpId
     *
     * @mbggenerated
     */
    public Long getIpid() {
        return ipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_ip.IpId
     *
     * @param ipid the value for mb_ip.IpId
     *
     * @mbggenerated
     */
    public void setIpid(Long ipid) {
        this.ipid = ipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_ip.IpAddress
     *
     * @return the value of mb_ip.IpAddress
     *
     * @mbggenerated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_ip.IpAddress
     *
     * @param ipaddress the value for mb_ip.IpAddress
     *
     * @mbggenerated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_ip.AccessTime
     *
     * @return the value of mb_ip.AccessTime
     *
     * @mbggenerated
     */
    public Date getAccesstime() {
        return accesstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_ip.AccessTime
     *
     * @param accesstime the value for mb_ip.AccessTime
     *
     * @mbggenerated
     */
    public void setAccesstime(Date accesstime) {
        this.accesstime = accesstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_ip.IpStats
     *
     * @return the value of mb_ip.IpStats
     *
     * @mbggenerated
     */
    public Short getIpstats() {
        return ipstats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_ip.IpStats
     *
     * @param ipstats the value for mb_ip.IpStats
     *
     * @mbggenerated
     */
    public void setIpstats(Short ipstats) {
        this.ipstats = ipstats;
    }
}