package com.qingyun.mybatis.model;

import java.util.Date;

public class MbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order.OrderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order.OrderNumber
     *
     * @mbggenerated
     */
    private String ordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order.OutTradeNo
     *
     * @mbggenerated
     */
    private String outtradeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order.PaymentType
     *
     * @mbggenerated
     */
    private Integer paymenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_order.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order.OrderId
     *
     * @return the value of mb_order.OrderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order.OrderId
     *
     * @param orderid the value for mb_order.OrderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order.OrderNumber
     *
     * @return the value of mb_order.OrderNumber
     *
     * @mbggenerated
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order.OrderNumber
     *
     * @param ordernumber the value for mb_order.OrderNumber
     *
     * @mbggenerated
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order.OutTradeNo
     *
     * @return the value of mb_order.OutTradeNo
     *
     * @mbggenerated
     */
    public String getOuttradeno() {
        return outtradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order.OutTradeNo
     *
     * @param outtradeno the value for mb_order.OutTradeNo
     *
     * @mbggenerated
     */
    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order.PaymentType
     *
     * @return the value of mb_order.PaymentType
     *
     * @mbggenerated
     */
    public Integer getPaymenttype() {
        return paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order.PaymentType
     *
     * @param paymenttype the value for mb_order.PaymentType
     *
     * @mbggenerated
     */
    public void setPaymenttype(Integer paymenttype) {
        this.paymenttype = paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_order.CreateTime
     *
     * @return the value of mb_order.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_order.CreateTime
     *
     * @param createtime the value for mb_order.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}