package com.qingyun.mybatis.model;

import java.util.Date;

public class MbProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductTitle
     *
     * @mbggenerated
     */
    private String producttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductState
     *
     * @mbggenerated
     */
    private Integer productstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductSort
     *
     * @mbggenerated
     */
    private Integer productsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductPic
     *
     * @mbggenerated
     */
    private String productpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.CreationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductRemarks
     *
     * @mbggenerated
     */
    private String productremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.IsDel
     *
     * @mbggenerated
     */
    private Short isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_product.ProductContext
     *
     * @mbggenerated
     */
    private String productcontext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductId
     *
     * @return the value of mb_product.ProductId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductId
     *
     * @param productid the value for mb_product.ProductId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductTitle
     *
     * @return the value of mb_product.ProductTitle
     *
     * @mbggenerated
     */
    public String getProducttitle() {
        return producttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductTitle
     *
     * @param producttitle the value for mb_product.ProductTitle
     *
     * @mbggenerated
     */
    public void setProducttitle(String producttitle) {
        this.producttitle = producttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductState
     *
     * @return the value of mb_product.ProductState
     *
     * @mbggenerated
     */
    public Integer getProductstate() {
        return productstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductState
     *
     * @param productstate the value for mb_product.ProductState
     *
     * @mbggenerated
     */
    public void setProductstate(Integer productstate) {
        this.productstate = productstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductSort
     *
     * @return the value of mb_product.ProductSort
     *
     * @mbggenerated
     */
    public Integer getProductsort() {
        return productsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductSort
     *
     * @param productsort the value for mb_product.ProductSort
     *
     * @mbggenerated
     */
    public void setProductsort(Integer productsort) {
        this.productsort = productsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductPic
     *
     * @return the value of mb_product.ProductPic
     *
     * @mbggenerated
     */
    public String getProductpic() {
        return productpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductPic
     *
     * @param productpic the value for mb_product.ProductPic
     *
     * @mbggenerated
     */
    public void setProductpic(String productpic) {
        this.productpic = productpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.CreationTime
     *
     * @return the value of mb_product.CreationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.CreationTime
     *
     * @param creationtime the value for mb_product.CreationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductRemarks
     *
     * @return the value of mb_product.ProductRemarks
     *
     * @mbggenerated
     */
    public String getProductremarks() {
        return productremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductRemarks
     *
     * @param productremarks the value for mb_product.ProductRemarks
     *
     * @mbggenerated
     */
    public void setProductremarks(String productremarks) {
        this.productremarks = productremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.IsDel
     *
     * @return the value of mb_product.IsDel
     *
     * @mbggenerated
     */
    public Short getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.IsDel
     *
     * @param isdel the value for mb_product.IsDel
     *
     * @mbggenerated
     */
    public void setIsdel(Short isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.category_id
     *
     * @return the value of mb_product.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.category_id
     *
     * @param categoryId the value for mb_product.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.key_word
     *
     * @return the value of mb_product.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.key_word
     *
     * @param keyWord the value for mb_product.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.description
     *
     * @return the value of mb_product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.description
     *
     * @param description the value for mb_product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_product.ProductContext
     *
     * @return the value of mb_product.ProductContext
     *
     * @mbggenerated
     */
    public String getProductcontext() {
        return productcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_product.ProductContext
     *
     * @param productcontext the value for mb_product.ProductContext
     *
     * @mbggenerated
     */
    public void setProductcontext(String productcontext) {
        this.productcontext = productcontext;
    }
}