package com.qingyun.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class MbShoppingmallExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public MbShoppingmallExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShoppingmallidIsNull() {
            addCriterion("ShoppingMallId is null");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidIsNotNull() {
            addCriterion("ShoppingMallId is not null");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidEqualTo(Long value) {
            addCriterion("ShoppingMallId =", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidNotEqualTo(Long value) {
            addCriterion("ShoppingMallId <>", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidGreaterThan(Long value) {
            addCriterion("ShoppingMallId >", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidGreaterThanOrEqualTo(Long value) {
            addCriterion("ShoppingMallId >=", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidLessThan(Long value) {
            addCriterion("ShoppingMallId <", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidLessThanOrEqualTo(Long value) {
            addCriterion("ShoppingMallId <=", value, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidIn(List<Long> values) {
            addCriterion("ShoppingMallId in", values, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidNotIn(List<Long> values) {
            addCriterion("ShoppingMallId not in", values, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidBetween(Long value1, Long value2) {
            addCriterion("ShoppingMallId between", value1, value2, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallidNotBetween(Long value1, Long value2) {
            addCriterion("ShoppingMallId not between", value1, value2, "shoppingmallid");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicIsNull() {
            addCriterion("ShoppingMallPic is null");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicIsNotNull() {
            addCriterion("ShoppingMallPic is not null");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicEqualTo(String value) {
            addCriterion("ShoppingMallPic =", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicNotEqualTo(String value) {
            addCriterion("ShoppingMallPic <>", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicGreaterThan(String value) {
            addCriterion("ShoppingMallPic >", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicGreaterThanOrEqualTo(String value) {
            addCriterion("ShoppingMallPic >=", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicLessThan(String value) {
            addCriterion("ShoppingMallPic <", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicLessThanOrEqualTo(String value) {
            addCriterion("ShoppingMallPic <=", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicLike(String value) {
            addCriterion("ShoppingMallPic like", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicNotLike(String value) {
            addCriterion("ShoppingMallPic not like", value, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicIn(List<String> values) {
            addCriterion("ShoppingMallPic in", values, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicNotIn(List<String> values) {
            addCriterion("ShoppingMallPic not in", values, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicBetween(String value1, String value2) {
            addCriterion("ShoppingMallPic between", value1, value2, "shoppingmallpic");
            return (Criteria) this;
        }

        public Criteria andShoppingmallpicNotBetween(String value1, String value2) {
            addCriterion("ShoppingMallPic not between", value1, value2, "shoppingmallpic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}