package com.qingyun.mybatis.model;

import java.util.Date;

public class MbSoftware {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.SoftwareId
     *
     * @mbggenerated
     */
    private Long softwareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.SoftwareTitle
     *
     * @mbggenerated
     */
    private String softwaretitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.SoftwarePic
     *
     * @mbggenerated
     */
    private String softwarepic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.CreationTime
     *
     * @mbggenerated
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.SoftwareRemarks
     *
     * @mbggenerated
     */
    private String softwareremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.iPhoneAddress
     *
     * @mbggenerated
     */
    private String iphoneaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.AndroidAddress
     *
     * @mbggenerated
     */
    private String androidaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.QRCode
     *
     * @mbggenerated
     */
    private String qrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.TitlePic
     *
     * @mbggenerated
     */
    private String titlepic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.iPhoneQRCode
     *
     * @mbggenerated
     */
    private String iphoneqrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mb_software.AndroidQRCode
     *
     * @mbggenerated
     */
    private String androidqrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.SoftwareId
     *
     * @return the value of mb_software.SoftwareId
     *
     * @mbggenerated
     */
    public Long getSoftwareid() {
        return softwareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.SoftwareId
     *
     * @param softwareid the value for mb_software.SoftwareId
     *
     * @mbggenerated
     */
    public void setSoftwareid(Long softwareid) {
        this.softwareid = softwareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.SoftwareTitle
     *
     * @return the value of mb_software.SoftwareTitle
     *
     * @mbggenerated
     */
    public String getSoftwaretitle() {
        return softwaretitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.SoftwareTitle
     *
     * @param softwaretitle the value for mb_software.SoftwareTitle
     *
     * @mbggenerated
     */
    public void setSoftwaretitle(String softwaretitle) {
        this.softwaretitle = softwaretitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.SoftwarePic
     *
     * @return the value of mb_software.SoftwarePic
     *
     * @mbggenerated
     */
    public String getSoftwarepic() {
        return softwarepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.SoftwarePic
     *
     * @param softwarepic the value for mb_software.SoftwarePic
     *
     * @mbggenerated
     */
    public void setSoftwarepic(String softwarepic) {
        this.softwarepic = softwarepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.CreationTime
     *
     * @return the value of mb_software.CreationTime
     *
     * @mbggenerated
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.CreationTime
     *
     * @param creationtime the value for mb_software.CreationTime
     *
     * @mbggenerated
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.SoftwareRemarks
     *
     * @return the value of mb_software.SoftwareRemarks
     *
     * @mbggenerated
     */
    public String getSoftwareremarks() {
        return softwareremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.SoftwareRemarks
     *
     * @param softwareremarks the value for mb_software.SoftwareRemarks
     *
     * @mbggenerated
     */
    public void setSoftwareremarks(String softwareremarks) {
        this.softwareremarks = softwareremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.iPhoneAddress
     *
     * @return the value of mb_software.iPhoneAddress
     *
     * @mbggenerated
     */
    public String getIphoneaddress() {
        return iphoneaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.iPhoneAddress
     *
     * @param iphoneaddress the value for mb_software.iPhoneAddress
     *
     * @mbggenerated
     */
    public void setIphoneaddress(String iphoneaddress) {
        this.iphoneaddress = iphoneaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.AndroidAddress
     *
     * @return the value of mb_software.AndroidAddress
     *
     * @mbggenerated
     */
    public String getAndroidaddress() {
        return androidaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.AndroidAddress
     *
     * @param androidaddress the value for mb_software.AndroidAddress
     *
     * @mbggenerated
     */
    public void setAndroidaddress(String androidaddress) {
        this.androidaddress = androidaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.QRCode
     *
     * @return the value of mb_software.QRCode
     *
     * @mbggenerated
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.QRCode
     *
     * @param qrcode the value for mb_software.QRCode
     *
     * @mbggenerated
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.TitlePic
     *
     * @return the value of mb_software.TitlePic
     *
     * @mbggenerated
     */
    public String getTitlepic() {
        return titlepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.TitlePic
     *
     * @param titlepic the value for mb_software.TitlePic
     *
     * @mbggenerated
     */
    public void setTitlepic(String titlepic) {
        this.titlepic = titlepic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.iPhoneQRCode
     *
     * @return the value of mb_software.iPhoneQRCode
     *
     * @mbggenerated
     */
    public String getIphoneqrcode() {
        return iphoneqrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.iPhoneQRCode
     *
     * @param iphoneqrcode the value for mb_software.iPhoneQRCode
     *
     * @mbggenerated
     */
    public void setIphoneqrcode(String iphoneqrcode) {
        this.iphoneqrcode = iphoneqrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mb_software.AndroidQRCode
     *
     * @return the value of mb_software.AndroidQRCode
     *
     * @mbggenerated
     */
    public String getAndroidqrcode() {
        return androidqrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mb_software.AndroidQRCode
     *
     * @param androidqrcode the value for mb_software.AndroidQRCode
     *
     * @mbggenerated
     */
    public void setAndroidqrcode(String androidqrcode) {
        this.androidqrcode = androidqrcode;
    }
}