package com.qingyun.mybatis.model;

import java.util.Date;

public class NewsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.newsinfo_id
     *
     * @mbggenerated
     */
    private Long newsinfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.news_titel
     *
     * @mbggenerated
     */
    private String newsTitel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.news_pic
     *
     * @mbggenerated
     */
    private String newsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.category_id
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.key_word
     *
     * @mbggenerated
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.news_content
     *
     * @mbggenerated
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.newsinfo_id
     *
     * @return the value of news_info.newsinfo_id
     *
     * @mbggenerated
     */
    public Long getNewsinfoId() {
        return newsinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.newsinfo_id
     *
     * @param newsinfoId the value for news_info.newsinfo_id
     *
     * @mbggenerated
     */
    public void setNewsinfoId(Long newsinfoId) {
        this.newsinfoId = newsinfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.news_titel
     *
     * @return the value of news_info.news_titel
     *
     * @mbggenerated
     */
    public String getNewsTitel() {
        return newsTitel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.news_titel
     *
     * @param newsTitel the value for news_info.news_titel
     *
     * @mbggenerated
     */
    public void setNewsTitel(String newsTitel) {
        this.newsTitel = newsTitel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.news_pic
     *
     * @return the value of news_info.news_pic
     *
     * @mbggenerated
     */
    public String getNewsPic() {
        return newsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.news_pic
     *
     * @param newsPic the value for news_info.news_pic
     *
     * @mbggenerated
     */
    public void setNewsPic(String newsPic) {
        this.newsPic = newsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.create_time
     *
     * @return the value of news_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.create_time
     *
     * @param createTime the value for news_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.edit_time
     *
     * @return the value of news_info.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.edit_time
     *
     * @param editTime the value for news_info.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.category_id
     *
     * @return the value of news_info.category_id
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.category_id
     *
     * @param categoryId the value for news_info.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.key_word
     *
     * @return the value of news_info.key_word
     *
     * @mbggenerated
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.key_word
     *
     * @param keyWord the value for news_info.key_word
     *
     * @mbggenerated
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.description
     *
     * @return the value of news_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.description
     *
     * @param description the value for news_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.news_content
     *
     * @return the value of news_info.news_content
     *
     * @mbggenerated
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.news_content
     *
     * @param newsContent the value for news_info.news_content
     *
     * @mbggenerated
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }
}