package com.qingyun.mybatis.model;

import java.util.Date;

public class SysFrinedshiplink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frinedshiplink.friendshiplink_id
     *
     * @mbggenerated
     */
    private Long friendshiplinkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frinedshiplink.friendshiplink_name
     *
     * @mbggenerated
     */
    private String friendshiplinkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frinedshiplink.friendshiplink_url
     *
     * @mbggenerated
     */
    private String friendshiplinkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frinedshiplink.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_frinedshiplink.edit_time
     *
     * @mbggenerated
     */
    private Date editTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frinedshiplink.friendshiplink_id
     *
     * @return the value of sys_frinedshiplink.friendshiplink_id
     *
     * @mbggenerated
     */
    public Long getFriendshiplinkId() {
        return friendshiplinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frinedshiplink.friendshiplink_id
     *
     * @param friendshiplinkId the value for sys_frinedshiplink.friendshiplink_id
     *
     * @mbggenerated
     */
    public void setFriendshiplinkId(Long friendshiplinkId) {
        this.friendshiplinkId = friendshiplinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frinedshiplink.friendshiplink_name
     *
     * @return the value of sys_frinedshiplink.friendshiplink_name
     *
     * @mbggenerated
     */
    public String getFriendshiplinkName() {
        return friendshiplinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frinedshiplink.friendshiplink_name
     *
     * @param friendshiplinkName the value for sys_frinedshiplink.friendshiplink_name
     *
     * @mbggenerated
     */
    public void setFriendshiplinkName(String friendshiplinkName) {
        this.friendshiplinkName = friendshiplinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frinedshiplink.friendshiplink_url
     *
     * @return the value of sys_frinedshiplink.friendshiplink_url
     *
     * @mbggenerated
     */
    public String getFriendshiplinkUrl() {
        return friendshiplinkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frinedshiplink.friendshiplink_url
     *
     * @param friendshiplinkUrl the value for sys_frinedshiplink.friendshiplink_url
     *
     * @mbggenerated
     */
    public void setFriendshiplinkUrl(String friendshiplinkUrl) {
        this.friendshiplinkUrl = friendshiplinkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frinedshiplink.create_time
     *
     * @return the value of sys_frinedshiplink.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frinedshiplink.create_time
     *
     * @param createTime the value for sys_frinedshiplink.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_frinedshiplink.edit_time
     *
     * @return the value of sys_frinedshiplink.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_frinedshiplink.edit_time
     *
     * @param editTime the value for sys_frinedshiplink.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }
}