package com.qingyun.mybatis.model;

import java.util.Date;

public class SysOpinionback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.OpinionBackId
     *
     * @mbggenerated
     */
    private Long opinionbackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.Phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.IsDel
     *
     * @mbggenerated
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_opinionback.Content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.OpinionBackId
     *
     * @return the value of sys_opinionback.OpinionBackId
     *
     * @mbggenerated
     */
    public Long getOpinionbackid() {
        return opinionbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.OpinionBackId
     *
     * @param opinionbackid the value for sys_opinionback.OpinionBackId
     *
     * @mbggenerated
     */
    public void setOpinionbackid(Long opinionbackid) {
        this.opinionbackid = opinionbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.UserName
     *
     * @return the value of sys_opinionback.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.UserName
     *
     * @param username the value for sys_opinionback.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.Phone
     *
     * @return the value of sys_opinionback.Phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.Phone
     *
     * @param phone the value for sys_opinionback.Phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.CreateTime
     *
     * @return the value of sys_opinionback.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.CreateTime
     *
     * @param createtime the value for sys_opinionback.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.IsDel
     *
     * @return the value of sys_opinionback.IsDel
     *
     * @mbggenerated
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.IsDel
     *
     * @param isdel the value for sys_opinionback.IsDel
     *
     * @mbggenerated
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_opinionback.Content
     *
     * @return the value of sys_opinionback.Content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_opinionback.Content
     *
     * @param content the value for sys_opinionback.Content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
}