package com.qingyun.mybatis.model;

public class SysText {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_text.TextId
     *
     * @mbggenerated
     */
    private Integer textid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_text.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_text.Text
     *
     * @mbggenerated
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_text.TitleUrl
     *
     * @mbggenerated
     */
    private String titleurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_text.BackgroudUrl
     *
     * @mbggenerated
     */
    private String backgroudurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_text.TextId
     *
     * @return the value of sys_text.TextId
     *
     * @mbggenerated
     */
    public Integer getTextid() {
        return textid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_text.TextId
     *
     * @param textid the value for sys_text.TextId
     *
     * @mbggenerated
     */
    public void setTextid(Integer textid) {
        this.textid = textid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_text.Title
     *
     * @return the value of sys_text.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_text.Title
     *
     * @param title the value for sys_text.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_text.Text
     *
     * @return the value of sys_text.Text
     *
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_text.Text
     *
     * @param text the value for sys_text.Text
     *
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_text.TitleUrl
     *
     * @return the value of sys_text.TitleUrl
     *
     * @mbggenerated
     */
    public String getTitleurl() {
        return titleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_text.TitleUrl
     *
     * @param titleurl the value for sys_text.TitleUrl
     *
     * @mbggenerated
     */
    public void setTitleurl(String titleurl) {
        this.titleurl = titleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_text.BackgroudUrl
     *
     * @return the value of sys_text.BackgroudUrl
     *
     * @mbggenerated
     */
    public String getBackgroudurl() {
        return backgroudurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_text.BackgroudUrl
     *
     * @param backgroudurl the value for sys_text.BackgroudUrl
     *
     * @mbggenerated
     */
    public void setBackgroudurl(String backgroudurl) {
        this.backgroudurl = backgroudurl;
    }
}