package com.qingyun.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class SysTextExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public SysTextExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTextidIsNull() {
            addCriterion("TextId is null");
            return (Criteria) this;
        }

        public Criteria andTextidIsNotNull() {
            addCriterion("TextId is not null");
            return (Criteria) this;
        }

        public Criteria andTextidEqualTo(Integer value) {
            addCriterion("TextId =", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidNotEqualTo(Integer value) {
            addCriterion("TextId <>", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidGreaterThan(Integer value) {
            addCriterion("TextId >", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidGreaterThanOrEqualTo(Integer value) {
            addCriterion("TextId >=", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidLessThan(Integer value) {
            addCriterion("TextId <", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidLessThanOrEqualTo(Integer value) {
            addCriterion("TextId <=", value, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidIn(List<Integer> values) {
            addCriterion("TextId in", values, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidNotIn(List<Integer> values) {
            addCriterion("TextId not in", values, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidBetween(Integer value1, Integer value2) {
            addCriterion("TextId between", value1, value2, "textid");
            return (Criteria) this;
        }

        public Criteria andTextidNotBetween(Integer value1, Integer value2) {
            addCriterion("TextId not between", value1, value2, "textid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTextIsNull() {
            addCriterion("Text is null");
            return (Criteria) this;
        }

        public Criteria andTextIsNotNull() {
            addCriterion("Text is not null");
            return (Criteria) this;
        }

        public Criteria andTextEqualTo(String value) {
            addCriterion("Text =", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotEqualTo(String value) {
            addCriterion("Text <>", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThan(String value) {
            addCriterion("Text >", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThanOrEqualTo(String value) {
            addCriterion("Text >=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThan(String value) {
            addCriterion("Text <", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThanOrEqualTo(String value) {
            addCriterion("Text <=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLike(String value) {
            addCriterion("Text like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotLike(String value) {
            addCriterion("Text not like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextIn(List<String> values) {
            addCriterion("Text in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotIn(List<String> values) {
            addCriterion("Text not in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextBetween(String value1, String value2) {
            addCriterion("Text between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotBetween(String value1, String value2) {
            addCriterion("Text not between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andTitleurlIsNull() {
            addCriterion("TitleUrl is null");
            return (Criteria) this;
        }

        public Criteria andTitleurlIsNotNull() {
            addCriterion("TitleUrl is not null");
            return (Criteria) this;
        }

        public Criteria andTitleurlEqualTo(String value) {
            addCriterion("TitleUrl =", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlNotEqualTo(String value) {
            addCriterion("TitleUrl <>", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlGreaterThan(String value) {
            addCriterion("TitleUrl >", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlGreaterThanOrEqualTo(String value) {
            addCriterion("TitleUrl >=", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlLessThan(String value) {
            addCriterion("TitleUrl <", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlLessThanOrEqualTo(String value) {
            addCriterion("TitleUrl <=", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlLike(String value) {
            addCriterion("TitleUrl like", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlNotLike(String value) {
            addCriterion("TitleUrl not like", value, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlIn(List<String> values) {
            addCriterion("TitleUrl in", values, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlNotIn(List<String> values) {
            addCriterion("TitleUrl not in", values, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlBetween(String value1, String value2) {
            addCriterion("TitleUrl between", value1, value2, "titleurl");
            return (Criteria) this;
        }

        public Criteria andTitleurlNotBetween(String value1, String value2) {
            addCriterion("TitleUrl not between", value1, value2, "titleurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlIsNull() {
            addCriterion("BackgroudUrl is null");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlIsNotNull() {
            addCriterion("BackgroudUrl is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlEqualTo(String value) {
            addCriterion("BackgroudUrl =", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlNotEqualTo(String value) {
            addCriterion("BackgroudUrl <>", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlGreaterThan(String value) {
            addCriterion("BackgroudUrl >", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlGreaterThanOrEqualTo(String value) {
            addCriterion("BackgroudUrl >=", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlLessThan(String value) {
            addCriterion("BackgroudUrl <", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlLessThanOrEqualTo(String value) {
            addCriterion("BackgroudUrl <=", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlLike(String value) {
            addCriterion("BackgroudUrl like", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlNotLike(String value) {
            addCriterion("BackgroudUrl not like", value, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlIn(List<String> values) {
            addCriterion("BackgroudUrl in", values, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlNotIn(List<String> values) {
            addCriterion("BackgroudUrl not in", values, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlBetween(String value1, String value2) {
            addCriterion("BackgroudUrl between", value1, value2, "backgroudurl");
            return (Criteria) this;
        }

        public Criteria andBackgroudurlNotBetween(String value1, String value2) {
            addCriterion("BackgroudUrl not between", value1, value2, "backgroudurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_text
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_text
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}