package com.qingyun.mybatis.model;

public class SysBasics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_basics.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_basics.LogoPic
     *
     * @mbggenerated
     */
    private String logopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_basics.VXCode
     *
     * @mbggenerated
     */
    private String vxcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_basics.BackgroudPic
     *
     * @mbggenerated
     */
    private String backgroudpic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_basics.Id
     *
     * @return the value of sys_basics.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_basics.Id
     *
     * @param id the value for sys_basics.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_basics.LogoPic
     *
     * @return the value of sys_basics.LogoPic
     *
     * @mbggenerated
     */
    public String getLogopic() {
        return logopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_basics.LogoPic
     *
     * @param logopic the value for sys_basics.LogoPic
     *
     * @mbggenerated
     */
    public void setLogopic(String logopic) {
        this.logopic = logopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_basics.VXCode
     *
     * @return the value of sys_basics.VXCode
     *
     * @mbggenerated
     */
    public String getVxcode() {
        return vxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_basics.VXCode
     *
     * @param vxcode the value for sys_basics.VXCode
     *
     * @mbggenerated
     */
    public void setVxcode(String vxcode) {
        this.vxcode = vxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_basics.BackgroudPic
     *
     * @return the value of sys_basics.BackgroudPic
     *
     * @mbggenerated
     */
    public String getBackgroudpic() {
        return backgroudpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_basics.BackgroudPic
     *
     * @param backgroudpic the value for sys_basics.BackgroudPic
     *
     * @mbggenerated
     */
    public void setBackgroudpic(String backgroudpic) {
        this.backgroudpic = backgroudpic;
    }
}