# 生产环境
# 端口设置
server:
  port: 8886
#  servlet:
#    # 设置访问前缀
#    context-path: /api

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qingyun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456q

  # redis配置
  redis:
    #  数据库索引
    database: 0
    # 链接超时时间（毫秒）
    timeout: 200
    # Redis服务器地址
    host: 39.96.59.248
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0

# logger配置
logging:
  level:
    #org.springframework.web: INFO,CONSOLE
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback/logback-pro.xml