package com.qingyun.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MbCooperativepartnerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public MbCooperativepartnerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCooperativepartneridIsNull() {
            addCriterion("CooperativePartnerId is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridIsNotNull() {
            addCriterion("CooperativePartnerId is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridEqualTo(Long value) {
            addCriterion("CooperativePartnerId =", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridNotEqualTo(Long value) {
            addCriterion("CooperativePartnerId <>", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridGreaterThan(Long value) {
            addCriterion("CooperativePartnerId >", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridGreaterThanOrEqualTo(Long value) {
            addCriterion("CooperativePartnerId >=", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridLessThan(Long value) {
            addCriterion("CooperativePartnerId <", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridLessThanOrEqualTo(Long value) {
            addCriterion("CooperativePartnerId <=", value, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridIn(List<Long> values) {
            addCriterion("CooperativePartnerId in", values, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridNotIn(List<Long> values) {
            addCriterion("CooperativePartnerId not in", values, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridBetween(Long value1, Long value2) {
            addCriterion("CooperativePartnerId between", value1, value2, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartneridNotBetween(Long value1, Long value2) {
            addCriterion("CooperativePartnerId not between", value1, value2, "cooperativepartnerid");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameIsNull() {
            addCriterion("CooperativePartnerName is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameIsNotNull() {
            addCriterion("CooperativePartnerName is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameEqualTo(String value) {
            addCriterion("CooperativePartnerName =", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameNotEqualTo(String value) {
            addCriterion("CooperativePartnerName <>", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameGreaterThan(String value) {
            addCriterion("CooperativePartnerName >", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameGreaterThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerName >=", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameLessThan(String value) {
            addCriterion("CooperativePartnerName <", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameLessThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerName <=", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameLike(String value) {
            addCriterion("CooperativePartnerName like", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameNotLike(String value) {
            addCriterion("CooperativePartnerName not like", value, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameIn(List<String> values) {
            addCriterion("CooperativePartnerName in", values, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameNotIn(List<String> values) {
            addCriterion("CooperativePartnerName not in", values, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameBetween(String value1, String value2) {
            addCriterion("CooperativePartnerName between", value1, value2, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnernameNotBetween(String value1, String value2) {
            addCriterion("CooperativePartnerName not between", value1, value2, "cooperativepartnername");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateIsNull() {
            addCriterion("CooperativePartnerState is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateIsNotNull() {
            addCriterion("CooperativePartnerState is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateEqualTo(Integer value) {
            addCriterion("CooperativePartnerState =", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateNotEqualTo(Integer value) {
            addCriterion("CooperativePartnerState <>", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateGreaterThan(Integer value) {
            addCriterion("CooperativePartnerState >", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("CooperativePartnerState >=", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateLessThan(Integer value) {
            addCriterion("CooperativePartnerState <", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateLessThanOrEqualTo(Integer value) {
            addCriterion("CooperativePartnerState <=", value, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateIn(List<Integer> values) {
            addCriterion("CooperativePartnerState in", values, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateNotIn(List<Integer> values) {
            addCriterion("CooperativePartnerState not in", values, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateBetween(Integer value1, Integer value2) {
            addCriterion("CooperativePartnerState between", value1, value2, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerstateNotBetween(Integer value1, Integer value2) {
            addCriterion("CooperativePartnerState not between", value1, value2, "cooperativepartnerstate");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortIsNull() {
            addCriterion("CooperativePartnerSort is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortIsNotNull() {
            addCriterion("CooperativePartnerSort is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortEqualTo(Integer value) {
            addCriterion("CooperativePartnerSort =", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortNotEqualTo(Integer value) {
            addCriterion("CooperativePartnerSort <>", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortGreaterThan(Integer value) {
            addCriterion("CooperativePartnerSort >", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortGreaterThanOrEqualTo(Integer value) {
            addCriterion("CooperativePartnerSort >=", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortLessThan(Integer value) {
            addCriterion("CooperativePartnerSort <", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortLessThanOrEqualTo(Integer value) {
            addCriterion("CooperativePartnerSort <=", value, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortIn(List<Integer> values) {
            addCriterion("CooperativePartnerSort in", values, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortNotIn(List<Integer> values) {
            addCriterion("CooperativePartnerSort not in", values, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortBetween(Integer value1, Integer value2) {
            addCriterion("CooperativePartnerSort between", value1, value2, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnersortNotBetween(Integer value1, Integer value2) {
            addCriterion("CooperativePartnerSort not between", value1, value2, "cooperativepartnersort");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicIsNull() {
            addCriterion("CooperativePartnerPic is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicIsNotNull() {
            addCriterion("CooperativePartnerPic is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicEqualTo(String value) {
            addCriterion("CooperativePartnerPic =", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicNotEqualTo(String value) {
            addCriterion("CooperativePartnerPic <>", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicGreaterThan(String value) {
            addCriterion("CooperativePartnerPic >", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicGreaterThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerPic >=", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicLessThan(String value) {
            addCriterion("CooperativePartnerPic <", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicLessThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerPic <=", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicLike(String value) {
            addCriterion("CooperativePartnerPic like", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicNotLike(String value) {
            addCriterion("CooperativePartnerPic not like", value, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicIn(List<String> values) {
            addCriterion("CooperativePartnerPic in", values, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicNotIn(List<String> values) {
            addCriterion("CooperativePartnerPic not in", values, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicBetween(String value1, String value2) {
            addCriterion("CooperativePartnerPic between", value1, value2, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerpicNotBetween(String value1, String value2) {
            addCriterion("CooperativePartnerPic not between", value1, value2, "cooperativepartnerpic");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNull() {
            addCriterion("CreationTime is null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIsNotNull() {
            addCriterion("CreationTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreationtimeEqualTo(Date value) {
            addCriterion("CreationTime =", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotEqualTo(Date value) {
            addCriterion("CreationTime <>", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThan(Date value) {
            addCriterion("CreationTime >", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreationTime >=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThan(Date value) {
            addCriterion("CreationTime <", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeLessThanOrEqualTo(Date value) {
            addCriterion("CreationTime <=", value, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeIn(List<Date> values) {
            addCriterion("CreationTime in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotIn(List<Date> values) {
            addCriterion("CreationTime not in", values, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeBetween(Date value1, Date value2) {
            addCriterion("CreationTime between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCreationtimeNotBetween(Date value1, Date value2) {
            addCriterion("CreationTime not between", value1, value2, "creationtime");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeIsNull() {
            addCriterion("CooperativePartnerDescribe is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeIsNotNull() {
            addCriterion("CooperativePartnerDescribe is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeEqualTo(String value) {
            addCriterion("CooperativePartnerDescribe =", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeNotEqualTo(String value) {
            addCriterion("CooperativePartnerDescribe <>", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeGreaterThan(String value) {
            addCriterion("CooperativePartnerDescribe >", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeGreaterThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerDescribe >=", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeLessThan(String value) {
            addCriterion("CooperativePartnerDescribe <", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeLessThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerDescribe <=", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeLike(String value) {
            addCriterion("CooperativePartnerDescribe like", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeNotLike(String value) {
            addCriterion("CooperativePartnerDescribe not like", value, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeIn(List<String> values) {
            addCriterion("CooperativePartnerDescribe in", values, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeNotIn(List<String> values) {
            addCriterion("CooperativePartnerDescribe not in", values, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeBetween(String value1, String value2) {
            addCriterion("CooperativePartnerDescribe between", value1, value2, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnerdescribeNotBetween(String value1, String value2) {
            addCriterion("CooperativePartnerDescribe not between", value1, value2, "cooperativepartnerdescribe");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("IsDel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("IsDel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Short value) {
            addCriterion("IsDel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Short value) {
            addCriterion("IsDel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Short value) {
            addCriterion("IsDel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Short value) {
            addCriterion("IsDel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Short value) {
            addCriterion("IsDel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Short value) {
            addCriterion("IsDel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Short> values) {
            addCriterion("IsDel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Short> values) {
            addCriterion("IsDel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Short value1, Short value2) {
            addCriterion("IsDel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Short value1, Short value2) {
            addCriterion("IsDel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentIsNull() {
            addCriterion("CooperativePartnerContent is null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentIsNotNull() {
            addCriterion("CooperativePartnerContent is not null");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentEqualTo(String value) {
            addCriterion("CooperativePartnerContent =", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentNotEqualTo(String value) {
            addCriterion("CooperativePartnerContent <>", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentGreaterThan(String value) {
            addCriterion("CooperativePartnerContent >", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentGreaterThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerContent >=", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentLessThan(String value) {
            addCriterion("CooperativePartnerContent <", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentLessThanOrEqualTo(String value) {
            addCriterion("CooperativePartnerContent <=", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentLike(String value) {
            addCriterion("CooperativePartnerContent like", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentNotLike(String value) {
            addCriterion("CooperativePartnerContent not like", value, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentIn(List<String> values) {
            addCriterion("CooperativePartnerContent in", values, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentNotIn(List<String> values) {
            addCriterion("CooperativePartnerContent not in", values, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentBetween(String value1, String value2) {
            addCriterion("CooperativePartnerContent between", value1, value2, "cooperativepartnercontent");
            return (Criteria) this;
        }

        public Criteria andCooperativepartnercontentNotBetween(String value1, String value2) {
            addCriterion("CooperativePartnerContent not between", value1, value2, "cooperativepartnercontent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mb_cooperativepartner
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}