package com.qingyun.mybatis.dao;

import com.qingyun.mybatis.model.MbShoppingmall;
import com.qingyun.mybatis.model.MbShoppingmallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MbShoppingmallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int countByExample(MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int deleteByExample(MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long shoppingmallid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int insert(MbShoppingmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int insertSelective(MbShoppingmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    List<MbShoppingmall> selectByExampleWithBLOBs(MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    List<MbShoppingmall> selectByExample(MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    MbShoppingmall selectByPrimaryKey(Long shoppingmallid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MbShoppingmall record, @Param("example") MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MbShoppingmall record, @Param("example") MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MbShoppingmall record, @Param("example") MbShoppingmallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MbShoppingmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(MbShoppingmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mb_shoppingmall
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MbShoppingmall record);
}